config/routes.rb
Rails.application.routes.draw do
  get "401", to: "errors#unauthorized", as: :unauthorized_error
  get "403", to: "errors#forbidden", as: :forbidden_error
  get "404", to: "errors#not_found", as: :not_found_error
  get "406", to: "errors#not_acceptable", as: :not_acceptable_error
  get "422", to: "errors#unprocessable_entity", as: :unprocessable_entity_error
  get "500", to: "errors#internal_server_error", as: :internal_server_error_error

  namespace :admin do
    resource :camp, only: [:show]

    resources :camp_applications do
      member do
        patch :active
        patch :approve
        patch :complete
        delete :force_delete
        patch :reject
        patch :restore
      end
    end

    resources :camp_deposits do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_dues do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_interviews do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        delete :force_delete
        patch :no_response
        patch :skip
        patch :reassign
        patch :restore
        patch :reject
      end
    end

    resources :camp_job_descriptions do
      member do
        patch :active
      end
    end

    resources :camp_jobs do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :skip
        patch :reject
      end
    end

    resources :camp_structures do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :reject
      end
    end

    resources :camp_tickets

    resources :camp_vehicles do
      member do
        patch :active
        patch :approve
        patch :complete
        patch :reject
      end
    end

    resources :camp_work_access_passes do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :reject
        patch :remove_ticket
      end
    end

    resources :newsletters do
      collection do
        get :export
      end

      member do
        delete :force_delete
        patch :restore
        patch :unsubscribe
      end
    end

    resources :pages, only: [] do
      collection do
        get :system
      end
    end

    resources :users do
      collection do
        get :bay_area
        get :deleted
        get :interviewers
        get :print_all
      end

      member do
        patch :remove_avatar
        get :print
        patch :restore
      end
    end

    root to: "pages#home"
  end

  resources :camp_applications, except: [:destroy] do
    collection do
      get :start
    end
  end

  resources :camp_deposits, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_dues, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_interviews, only: [:index, :show] do
    member do
      patch :approve_or_reject
    end
  end

  resources :camp_job_descriptions, only: [:index, :show]
  resources :camp_jobs, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :camp_structures

  resources :camp_tickets

  resources :camp_vehicles

  resources :camp_work_access_passes, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :guides, only: [:index] do
    collection do
      get :build
      get :bunny_bar
      get :covid
      get :deposit
      get :disclaimer
      get :dues
      get :events
      get :history
      get :ice
      get :interview
      get :jobs
      get :kitchen
      get :lag_bolts
      get :learn
      get :map
      get :mayor_of_the_day
      get :outside_services
      get :parking
      get :power
      get :projects
      get :rules
      get :sauna
      get :shade
      get :shipping_container
      get :sound
      get :strike
      get :tickets
      get :tools
      get :trash
      get :work_access_pass
      get :yearbook
    end
  end

  resources :newsletters do
    member do
      patch :unsubscribe
    end
  end

  resources :pages, only: [] do
    collection do
      get :contact
      get :events
      get :history
    end
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_calbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  resources :users, only: [:index, :show, :edit] do
    member do
      patch :confirm
      get :ticket
    end

    collection do
      get :me
      get :search
      get :status
    end
  end

  root to: "pages#home"
end

app/controllers/admin/camp_interviews_controller.rb
module Admin
  class CampInterviewsController < ApplicationController
    include Admin::Campable

    # GET /admin/camp_interviews
    def index
      authorize([:admin, :camp_interview])
      @query = ::CampInterview.includes(:user, :interviewed_by).order(updated_at: :desc)

      @query = @query.for_interviewed_by(params[:search][:interviewed_by_id]) if params.dig(:search, :interviewed_by_id).present?

      @query = @query.with_status(params[:search][:status]) if params.dig(:search, :status).present?

      @pagy, @resources = pagy(@query)
    end

    # PATCH /admin/camp_interviews/:id/assign
    def assign
      set_resource

      @interviewed_by = ::User.for_id(params.dig(:camp_interview, :interviewed_by_id)).take
      @resource.assigned_at = Time.current
      @resource.assigned_by = current_user
      @resource.interviewed_by = @interviewed_by
      @resource.status = :assigned

      @resource.assign_attributes(permitted_attributes([:admin, @resource])) if params[:camp_interview].present?

      if @resource.save
        CampInterviewMailer.with(resource: @resource).assign.deliver_now if send_email?
        CampInterviewMailer.with(resource: @resource).new_interview.deliver_now if send_email?

        redirect_to([:admin, @resource], success: "Interview has been assigned to #{@interviewed_by}.", status: :see_other)
      else
        redirect_on_error
      end
    end

    # PATCH /admin/camp_interviews/:id/reassign
    def reassign
      set_resource

      @interviewed_by = ::User.for_id(params.dig(:camp_interview, :interviewed_by_id)).take
      @resource.assigned_at = Time.current
      @resource.assigned_by = current_user
      @resource.interviewed_by = @interviewed_by
      @resource.status = :assigned

      @resource.assign_attributes(permitted_attributes([:admin, @resource])) if params[:camp_interview].present?

      if @resource.save
        CampInterviewMailer.with(resource: @resource).reassign.deliver_now if send_email?
        CampInterviewMailer.with(resource: @resource).new_interview.deliver_now if send_email?

        redirect_to([:admin, @resource], success: "Interview has been reassigned to #{@interviewed_by}.", status: :see_other)
      else
        redirect_on_error
      end
    end

    private

    def approve_after_save
      return unless @resource.user.present?
      @resource.user.update(plan: :camping_with_us)

      CampInterviewMailer.with(resource: @resource).approve.deliver_now if send_email?
    end

    def complete_after_save
      return unless @resource.user.present?

      @resource.user.update(plan: :camping_with_us)
    end

    def reject_after_save
      return unless @resource.user.present?
      @resource.user.update(plan: :camping_elsewhere)

      CampInterviewMailer.with(resource: @resource).reject.deliver_now if send_email?
    end

    def skip_after_save
      return unless @resource.user.present?
      @resource.user.update(plan: :camping_with_us)
      @resource.update(interviewed_by: nil)

      CampInterviewMailer.with(resource: @resource).skip.deliver_now if send_email?
    end
  end
end

app/controllers/camp_interviews_controller.rb
class CampInterviewsController < ApplicationController
  include Campable

  # GET /camp_interviews
  def index
    authorize(:camp_interview)
    @assigned_camp_interviews_pagy, @assigned_camp_interviews = pagy(current_user.camp_interviews.with_status(:assigned).includes([:user, :assigned_by]))
    @finished_camp_interviews_pagy, @finished_camp_interviews = pagy(current_user.camp_interviews.with_status(:approved, :completed, :no_response, :rejected).includes([:user, :assigned_by, :interviewed_by]))
  end

  # PATCH /camp_interviews/:id/approve_or_reject
  def approve_or_reject
    set_resource

    @resource.assign_attributes(permitted_attributes(@resource))

    case params.dig(:camp_interview, :action)&.to_sym
    when :approved then approve
    when :rejected then reject
    when :no_response then no_response
    else
      no_action
    end

    render(
      turbo_stream: turbo_stream.replace(
        "approve_or_reject_card_#{@resource.index}",
        partial: "camp_interviews/approve_or_reject_card",
        locals: {index: @resource.index, camp_interview: @resource}
      )
    )
  end

  private

  def approve
    @resource.status = :approved
    @resource.approved_by = current_user
    @resource.approved_at = Time.current

    if @resource.save && @resource.user.present?
      CampInterviewMailer.with(resource: @resource).approve.deliver_now
      CampInterviewMailer.with(resource: @resource).admin_approve.deliver_now
      @resource.user.update(plan: :camping_with_us)
    end
  end

  def reject
    @resource.status = :rejected
    @resource.rejected_by = current_user
    @resource.rejected_at = Time.current

    if @resource.save && @resource.user.present?
      CampInterviewMailer.with(resource: @resource).reject.deliver_now
      CampInterviewMailer.with(resource: @resource).admin_reject.deliver_now
      @resource.user.update(plan: :camping_elsewhere)
    end
  end

  def no_response
    previous_status = @resource.status.to_sym
    @resource.status = :no_response
    @resource.no_response_by = current_user
    @resource.no_response_at = Time.current

    if @resource.save && @resource.user.present? && previous_status != :no_response
      CampInterviewMailer.with(resource: @resource).no_response.deliver_now
    end
  end

  def no_action
    @resource.errors.add(:action, "is required")
  end
end

app/helpers/camp_interview_helper.rb
module CampInterviewHelper
  def camp_interviews_count_badge(count)
    return na_badge unless count.present?

    if count.zero?
      success_count_badge(count)
    else
      warning_count_badge(count)
    end
  end
end

app/views/camp_interviews/_approve_or_reject_card.html.slim
= turbo_frame_tag("approve_or_reject_card_#{index}", target: "_top") do
  .card.mb-3
    = card_header("file-earmark-person", link_to_camp(camp_interview), buttons: [camp_status_badge(camp_interview)])

    - if camp_interview.approved? && camp_interview.valid?
      .card-body
        .alert.alert-success Interview has been <b>approved</b>.
        p.card-text #{link_to_user(camp_interview.user)} will be notified of their approval.
        p.card-text <b>Thank you</b> for contribuiting to camp!
    - elsif camp_interview.rejected? && camp_interview.valid?
      .card-body
        .alert.alert-danger Interview has been <b>rejected</b>.
        p.card-text #{link_to_user(camp_interview.user)} will be notified of their rejection.
    - elsif camp_interview.no_response? && camp_interview.valid?
      .card-body
        .alert.alert-secondary Interview has been marked <b>no response</b>.
        p.card-text #{link_to_user(camp_interview.user)} will be notified.
    - elsif camp_interview.completed?
      .card-body
        .alert.alert-success Interview has been <b>completed</b>.
        p.card-text No further action is required.
    - else
      .card-table
        table.table
          tbody
            - if camp_interview.user.present?
              tr
                th User
                td = link_to_user(camp_interview.user)
            - if camp_interview.user&.camp_application.present?
              tr
                th Application
                td
                  = link_to_camp(camp_interview.user.camp_application)
                  =< camp_status_badge(camp_interview.user.camp_application)
            - if camp_interview.assigned_by.present?
              tr
                th Assigned by
                td = link_to_user(camp_interview.assigned_by)
            - if camp_interview.initial_notes.present?
              tr
                th Initial notes
                td = camp_interview.initial_notes
      .card-body
        = render "shared/error_messages", resource: camp_interview
        = simple_form_for(camp_interview, namespace: "form_#{index}", url: approve_or_reject_camp_interview_path(camp_interview)) do |f|
            = f.input :index, input_html: { value: index }, as: :hidden
            .row
              .col.mb-3
                = f.input :feedback_notes, hint: "sent to the user by email"
            .row
              .col.mb-3
                = f.input :private_notes, hint: "only visible to camp leadership, what did you think of them"
            .row
              .col.mb-3
                = f.input :action, as: :radio_buttons, hint: "decide if this person should camp with us", checked: camp_interview.status, collection: [[yes_badge("Approve"), "approved"], [no_badge("Reject"), "rejected"], [secondary_badge("No response"), "no_response"]]
            .row
              .col.d-grid
                = f.button :submit, "Submit", class: "btn-primary-override"

app/views/camp_interviews/_assigned_card.html.slim
- if policy(resource).me? && resource.assigned?
  .card.bg-info.bg-opacity-10.mb-3
    = card_header("people-fill", link_to_camp(resource, "Assigned interview"))
    .card-body
      p.card-text Your interview has been assigned to #{link_to_user(resource.interviewed_by)}.
      p.card-text Please contact them directly to schedule a time to complete your interview.
      - if policy(resource.interviewed_by).contact?
        p.card-text
          <b>Email</b> #{mail_to(resource.interviewed_by.email, target: "_blank")}
        p.card-text
          <b>Phone</b> #{link_to_phone(resource.interviewed_by.phone_number)}
        - if resource.interviewed_by.country_code.present?
          p.card-text <b>Country</b> #{resource.interviewed_by.country_name}
        p.card-text
          <b>Time zone</b> #{resource.interviewed_by.time_zone}

app/views/camp_interviews/_camp_interview_card.html.slim
.card.mb-3
  = card_header("file-earmark-person", link_to_camp(resource, "Interview"))
  .card-table
    table.table
      tbody
        tr
          th Status
          td = camp_status_badge(resource)
        tr
          th Feedback notes
          td = resource.feedback_notes.presence || na_badge
        tr
          th Interviewer
          td = link_to_user(resource.interviewed_by)
        - if resource.approved_at.present?
          tr
            th Approved
            td = admin_time(resource.approved_at)
        - if resource.skipped_at.present?
          tr
            th Skipped
            td = admin_time(resource.skipped_at)
        - if resource.completed_at.present?
          tr
            th Completed
            td = admin_time(resource.completed_at)
        tr
          th Created
          td = admin_time(resource.created_at)
        tr
          th Updated
          td = admin_time(resource.updated_at)
  .card-footer
    .btn-collection
      - if policy(current_user).me?
        = link_to("Back to profile", user_path(current_user), class: "btn btn-secondary")

app/views/camp_interviews/_empty_card.html.slim
.card.mb-3
  = card_header("file-earmark-person", "Interviews")
  .card-body
    .alert.alert-dark.mb-1 You don't currently have any assigned interviews.

app/views/camp_interviews/_finished_camp_interviews_card.html.slim
- if finished_camp_interviews.size.positive?
  .card.mb-3
        = card_header("file-earmark-person", "Finished interviews", pagy: pagy)
        .card-table
          table.table
            thead
              tr
                th ID
                th User
                th Status
                th Updated
                th Assigned by
                th
            tbody
              - finished_camp_interviews.each do |camp_interview|
                tr
                  td = link_to_id(camp_interview)
                  td = link_to_user(camp_interview.user)
                  td = camp_status_badge(camp_interview)
                  td = admin_time(camp_interview.updated_at)
                  td = link_to_user(camp_interview.assigned_by)
                  td.text-end = link_icon(camp_interview)
        = pagy_card_footer(pagy)

app/views/camp_interviews/_instructions_card.html.slim
 .card.mb-3
  = card_header("file-earmark-person", "Interviews", pagy: pagy)
  .card-body
    p.card-text The following interviews are assigned to you. Please approve or reject each one after meeting with the person.
    .alert.alert-info.mb-1 Learn more about the #{link_to_guide("interview", :interview)} process in our guide.

app/views/camp_interviews/index.html.slim
- page_title("Interviews")

.row
  .col-md-9
    - if @assigned_camp_interviews.empty?
      = render "empty_card"
    - else
      = render "instructions_card", pagy: @assigned_camp_interviews_pagy
  .col-md-3

.row
  - @assigned_camp_interviews.each_with_index do |camp_interview, index|
    .col-md-4
      = render "approve_or_reject_card", camp_interview: camp_interview, index: index

.row
  .col-md-9
    = render "finished_camp_interviews_card", finished_camp_interviews: @finished_camp_interviews, pagy: @finished_camp_interviews_pagy

app/views/camp_interviews/show.html.slim
- page_title(@resource)
= discard_alert(@resource)

.row
  .col-md-3
  .col-md-6
    = render "assigned_card", resource: @resource
    - if policy(@resource).interviewer?
       = render "approve_or_reject_card", camp_interview: @resource, index: 0
    = render "camp_interview_card", resource: @resource
  .col-md-3
    = render "admin_card", resource: @resource