config/routes.rb
Rails.application.routes.draw do
  get "401", to: "errors#unauthorized", as: :unauthorized_error
  get "403", to: "errors#forbidden", as: :forbidden_error
  get "404", to: "errors#not_found", as: :not_found_error
  get "406", to: "errors#not_acceptable", as: :not_acceptable_error
  get "422", to: "errors#unprocessable_entity", as: :unprocessable_entity_error
  get "500", to: "errors#internal_server_error", as: :internal_server_error_error

  namespace :admin do
    resource :camp, only: [:show]

    resources :camp_applications do
      member do
        patch :active
        patch :approve
        patch :complete
        delete :force_delete
        patch :reject
        patch :restore
      end
    end

    resources :camp_deposits do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_dues do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_interviews do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        delete :force_delete
        patch :no_response
        patch :skip
        patch :reassign
        patch :restore
        patch :reject
      end
    end

    resources :camp_job_descriptions do
      member do
        patch :active
      end
    end

    resources :camp_jobs do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :skip
        patch :reject
      end
    end

    resources :camp_structures do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :reject
      end
    end

    resources :camp_tickets

    resources :camp_vehicles do
      member do
        patch :active
        patch :approve
        patch :complete
        patch :reject
      end
    end

    resources :camp_work_access_passes do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :reject
        patch :remove_ticket
      end
    end

    resources :newsletters do
      collection do
        get :export
      end

      member do
        delete :force_delete
        patch :restore
        patch :unsubscribe
      end
    end

    resources :pages, only: [] do
      collection do
        get :system
      end
    end

    resources :users do
      collection do
        get :bay_area
        get :deleted
        get :interviewers
        get :print_all
      end

      member do
        patch :remove_avatar
        get :print
        patch :restore
      end
    end

    root to: "pages#home"
  end

  resources :camp_applications, except: [:destroy] do
    collection do
      get :start
    end
  end

  resources :camp_deposits, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_dues, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_interviews, only: [:index, :show] do
    member do
      patch :approve_or_reject
    end
  end

  resources :camp_job_descriptions, only: [:index, :show]
  resources :camp_jobs, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :camp_structures

  resources :camp_tickets

  resources :camp_vehicles

  resources :camp_work_access_passes, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :guides, only: [:index] do
    collection do
      get :build
      get :bunny_bar
      get :covid
      get :deposit
      get :disclaimer
      get :dues
      get :events
      get :history
      get :ice
      get :interview
      get :jobs
      get :kitchen
      get :lag_bolts
      get :learn
      get :map
      get :mayor_of_the_day
      get :outside_services
      get :parking
      get :power
      get :projects
      get :rules
      get :sauna
      get :shade
      get :shipping_container
      get :sound
      get :strike
      get :tickets
      get :tools
      get :trash
      get :work_access_pass
      get :yearbook
    end
  end

  resources :newsletters do
    member do
      patch :unsubscribe
    end
  end

  resources :pages, only: [] do
    collection do
      get :contact
      get :events
      get :history
    end
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_calbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  resources :users, only: [:index, :show, :edit] do
    member do
      patch :confirm
      get :ticket
    end

    collection do
      get :me
      get :search
      get :status
    end
  end

  root to: "pages#home"
end

app/models/camp_due.rb
# == Schema Information
#
# Table name: camp_dues
#
#  id              :bigint           not null, primary key
#  completed_at    :datetime
#  notes           :text
#  paid_at         :datetime
#  payment_method  :integer
#  price_cents     :integer          default(0), not null
#  price_currency  :string           default("USD"), not null
#  pricing_tier    :integer
#  private_notes   :text
#  refunded_at     :datetime
#  rejected_at     :datetime
#  skipped_at      :datetime
#  status          :integer          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  completed_by_id :bigint
#  paid_by_id      :bigint
#  refunded_by_id  :bigint
#  rejected_by_id  :bigint
#  skipped_by_id   :bigint
#  transaction_id  :string           not null
#  user_id         :bigint
#
# Indexes
#
#  index_camp_dues_on_user_id  (user_id)
#
class CampDue < ApplicationRecord
  extend Enumerize

  include Stepable
  include Transactable

  enumerize :status, in: STATUSES.slice(:active, :completed, :paid, :refunded, :rejected, :skipped), default: :active, predicates: true, scope: true

  belongs_to :user

  scope :finished, -> { with_status(:paid, :skipped, :completed) }

  def finished?
    completed? || paid? || skipped?
  end
end

app/controllers/admin/camp_dues_controller.rb
module Admin
  class CampDuesController < ApplicationController
    include Admin::Campable

    private

    def search_index
      @query = @query.for_transaction_id(params[:search][:transaction_id]) if params.dig(:search, :transaction_id).present?

      @camp_deposits_pagy, @camp_deposits = pagy(::CampDeposit.for_transaction_id(params[:search][:transaction_id]), page_param: :camp_deposit) if params.dig(:search, :transaction_id).present?
    end
  end
end

app/controllers/camp_dues_controller.rb
class CampDuesController < ApplicationController
  include Campable
  before_action :locked, only: [:create, :edit, :update, :pay]

  def after_create
    @redirect_url = camp_due_url(@resource)
  end

  def after_new
    redirect_to(camp_due_url(current_user.camp_due), notice: "It looks like you already started paying dues. Here is your current information.") if current_user&.camp_due.present?
  end
end

app/views/admin/camp_dues/_camp_due_card.html.slim
.card.mb-3
  = card_header("cash-coin", admin_link_to_camp(resource, "Dues"), buttons: [header_show_button(resource), header_admin_edit_button(resource)])
  .card-table
    table.table
      tbody
        tr
          th ID
          td = admin_link_to_id(resource)
        tr
          th User
          td = admin_link_to_user(resource.user)
        tr
          th Status
          td = camp_status_badge(resource)
        tr
          th Price
          td
            = number_to_currency(resource.price)
            =< camp_pricing_tier_badge(resource)
        tr
          th Payment method
          td = camp_payment_method_badge(resource)
        tr
          th Transaction ID
          td = resource.transaction_id
        tr
          th Notes
          td = resource.notes.presence || na_badge
        tr
          th Private notes
          td = resource.private_notes.presence || na_badge
        = render "admin/shared/status_times", resource: resource

app/views/admin/camp_dues/_form.html.slim
= render "shared/error_messages", resource: resource
= simple_form_for([:admin, resource]) do |f|
  .row
    .col-md-6.mb-3
      = f.input :status, include_blank: false
    .col-md-6.mb-3
      = user_id_input(resource, f)
  .row
    .col-md-6.mb-3
      = f.input :payment_method, include_blank: false
    .col-md-6.mb-3
      = f.input :pricing_tier, include_blank: false
  .row
    .col-md-6.mb-3
      = f.input :price
  .row
    .col-md-12.mb-3
      = f.input :private_notes
  .row
    .col.d-grid
      = f.button :submit, submit_button_text(resource)

app/views/admin/camp_dues/_search_card.html.slim
.card.mb-3
  = card_header("search", "Search")
  .card-form
    = simple_form_for(:search, url: admin_camp_dues_path, method: :get) do |f|
      .row
        .col-md-4.mb-3
           = f.input :transaction_id, hint: "ABC123", input_html: { value: params.dig(:search, :transaction_id) }, label: "Transaction ID", required: false
      .row
        .col.d-grid
          = f.button :button, "Search"

app/views/admin/camp_dues/_table_card.html.slim
.card.mb-3
  = card_header("cash-coin", "Dues", pagy: pagy, buttons: [header_admin_new_button(:camp_due)])
  .card-table
    table.table
      thead
        tr
          th ID
          th Transaction ID
          th User
          th Status
          th Price
          th Method
          th
      tbody
        - resources.each do |resource|
          tr
            td = admin_link_to_id(resource)
            td = admin_link_to_camp(resource, resource.transaction_id)
            td = admin_link_to_user(resource.user)
            td = camp_status_badge(resource)
            td = admin_link_to_camp(resource, number_to_currency(resource.price))
            td = camp_payment_method_badge(resource)
            td.text-end = admin_edit_icon(resource)
  = pagy_card_footer(pagy)

app/views/admin/camp_dues/edit.html.slim
- page_title("Edit #{@resource}")

.row
  .col-md-3
  .col-md-6
    .card.mb-3
      = card_header("cash-coin", "Dues", buttons: [header_admin_back_button(@resource)])
      .card-form
        = render "form", resource: @resource
  .col-md-3
    = render "admin_card", resource: @resource

app/views/admin/camp_dues/index.html.slim
- page_title("Dues")

.row
  .col-md-8
    = render "search_card"
.row
  .col-md-12
    = render "table_card", resources: @resources, pagy: @pagy

- if @camp_deposits.present?
  .row
    .col-md-12
      .alert.alert-warning We found deposits that look similar.
      = render "admin/camp_deposits/table_card", resources: @camp_deposits, pagy: @camp_deposits_pagy

app/views/admin/camp_dues/new.html.slim
- page_title("New - Dues")

.row
  .col-md-3
  .col-md-6
    .card.mb-3
      = card_header("cash-coin", "Dues")
      .card-form
        = render "form", resource: @resource
  .col-md-3

app/views/admin/camp_dues/show.html.slim
- page_title(@resource)

.row
  .col-md-3
  .col-md-6
    = render "camp_due_card", resource: @resource
  .col-md-3
    = render "admin_card", resource: @resource