config/routes.rb
Rails.application.routes.draw do
  get "401", to: "errors#unauthorized", as: :unauthorized_error
  get "403", to: "errors#forbidden", as: :forbidden_error
  get "404", to: "errors#not_found", as: :not_found_error
  get "406", to: "errors#not_acceptable", as: :not_acceptable_error
  get "422", to: "errors#unprocessable_entity", as: :unprocessable_entity_error
  get "500", to: "errors#internal_server_error", as: :internal_server_error_error

  namespace :admin do
    resource :camp, only: [:show]

    resources :camp_applications do
      member do
        patch :active
        patch :approve
        patch :complete
        delete :force_delete
        patch :reject
        patch :restore
      end
    end

    resources :camp_deposits do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_dues do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_interviews do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        delete :force_delete
        patch :no_response
        patch :skip
        patch :reassign
        patch :restore
        patch :reject
      end
    end

    resources :camp_job_descriptions do
      member do
        patch :active
      end
    end

    resources :camp_jobs do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :skip
        patch :reject
      end
    end

    resources :camp_structures do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :reject
      end
    end

    resources :camp_tickets

    resources :camp_vehicles do
      member do
        patch :active
        patch :approve
        patch :complete
        patch :reject
      end
    end

    resources :camp_work_access_passes do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :reject
        patch :remove_ticket
      end
    end

    resources :newsletters do
      collection do
        get :export
      end

      member do
        delete :force_delete
        patch :restore
        patch :unsubscribe
      end
    end

    resources :pages, only: [] do
      collection do
        get :system
      end
    end

    resources :users do
      collection do
        get :bay_area
        get :deleted
        get :interviewers
        get :print_all
      end

      member do
        patch :remove_avatar
        get :print
        patch :restore
      end
    end

    root to: "pages#home"
  end

  resources :camp_applications, except: [:destroy] do
    collection do
      get :start
    end
  end

  resources :camp_deposits, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_dues, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_interviews, only: [:index, :show] do
    member do
      patch :approve_or_reject
    end
  end

  resources :camp_job_descriptions, only: [:index, :show]
  resources :camp_jobs, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :camp_structures

  resources :camp_tickets

  resources :camp_vehicles

  resources :camp_work_access_passes, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :guides, only: [:index] do
    collection do
      get :build
      get :bunny_bar
      get :covid
      get :deposit
      get :disclaimer
      get :dues
      get :events
      get :history
      get :ice
      get :interview
      get :jobs
      get :kitchen
      get :lag_bolts
      get :learn
      get :map
      get :mayor_of_the_day
      get :outside_services
      get :parking
      get :power
      get :projects
      get :rules
      get :sauna
      get :shade
      get :shipping_container
      get :sound
      get :strike
      get :tickets
      get :tools
      get :trash
      get :work_access_pass
      get :yearbook
    end
  end

  resources :newsletters do
    member do
      patch :unsubscribe
    end
  end

  resources :pages, only: [] do
    collection do
      get :contact
      get :events
      get :history
    end
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_calbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  resources :users, only: [:index, :show, :edit] do
    member do
      patch :confirm
      get :ticket
    end

    collection do
      get :me
      get :search
      get :status
    end
  end

  root to: "pages#home"
end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id                :bigint           not null, primary key
#  discarded_at      :datetime
#  email             :string
#  list              :integer          not null
#  unsubscribe_token :string           not null
#  unsubscribed_at   :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :bigint
#
# Indexes
#
#  index_newsletters_on_discarded_at       (discarded_at)
#  index_newsletters_on_email              (email) UNIQUE
#  index_newsletters_on_unsubscribe_token  (unsubscribe_token) UNIQUE
#  index_newsletters_on_user_id            (user_id) UNIQUE
#
class Newsletter < ApplicationRecord
  extend Enumerize

  include Discard::Model
  include Validatable

  has_secure_token :unsubscribe_token, length: 36

  validates :email, presence: true
  validates :email, :unsubscribe_token, uniqueness: true
  validates :user_id, uniqueness: true, allow_blank: true
  validate :user_exists

  enumerize :list, in: {unsubscribed: 0, general: 1, campers_only: 2}, default: :unsubscribed, predicates: true, scope: true

  belongs_to :user, optional: true

  scope :for_email, ->(email) { where(email: email&.downcase&.squish) }
  scope :like_email, ->(email) { where("email LIKE ?", "%#{email&.downcase&.squish}%") }
  scope :for_user, ->(user) { where(user: user) }
  scope :without_user, -> { where(user_id: nil) }
  scope :subscribed, -> { with_list(:general, :campers_only) }
  scope :unsubscribed, -> { with_list(:unsubsribed) }

  before_validation :set_unsubscribed_at

  def to_s
    email
  end

  def to_log
    "Newsletter id=#{id}, email=#{email}"
  end

  def unsubscribe!
    update!(list: :unsubscribed, unsubscribed_at: Time.current)
  end

  def subscribed?
    !unsubscribed?
  end

  private

  def set_unsubscribed_at
    self.unsubscribed_at = nil if list != :unsubscribed
    self.unsubscribed_at = Time.current if list == :unsubscribed && unsubscribed_at.blank?
  end
end

app/controllers/admin/newsletters_controller.rb
module Admin
  class NewslettersController < ApplicationController
    include Sortable

    before_action :set_newsletter, only: [:show, :edit, :update, :destroy, :restore, :unsubscribe, :force_delete]

    # GET /admin/newsletters
    def index
      authorize([:admin, :newsletter])

      @query = ::Newsletter.includes(:user).kept
      @query = @query.like_email(params[:search][:email]) if params.dig(:search, :email).present?
      @query = @query.for_user(params[:search][:user_id]) if params.dig(:search, :user_id).present?
      @query = @query.with_list(params[:search][:list]) if params.dig(:search, :list).present?

      @query = @query.order(id: param_direction) if params[:column] == "id"
      @query = @query.order(email: param_direction) if params[:column] == "email"
      @query = @query.order(list: param_direction) if params[:column] == "list"

      @pagy, @newsletters = pagy(@query.order(created_at: :desc), items: 50)
    end

    # GET /admin/newsletters/:id
    def show
    end

    # GET /admin/newsletters/new
    def new
      @newsletter = ::Newsletter.new(email: params[:email], user_id: params[:user_id], list: :general)
      authorize([:admin, @newsletter])
    end

    # POST /admin/newsletters
    def create
      @newsletter = ::Newsletter.new(permitted_attributes([:admin, ::Newsletter]))
      authorize([:admin, @newsletter])
      if @newsletter.save
        redirect_to(admin_newsletter_url(@newsletter), success: "Newsletter was successfully created.")
      else
        render :new, status: :unprocessable_entity
      end
    end

    # GET /admin/newsletters/:id/edit
    def edit
    end

    # PATCH /admin/newsletters/:id
    def update
      if @newsletter.update(permitted_attributes([:admin, @newsletter]))
        redirect_to(admin_newsletter_url(@newsletter), success: "Newsletter was successfully updated.")
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /admin/newsletters/:id
    def destroy
      @newsletter.discard

      redirect_to(admin_newsletters_url, notice: "Newsletter was successfully destroyed.", status: :see_other)
    end

    # GET /admin/newsletters/export
    def export
      authorize([:admin, :newsletter])
      @general_list = ::Newsletter.with_list(:general).order(email: :asc)
      @general_list_text = @general_list.join(",\n")
      @campers_only_list = ::Newsletter.with_list(:campers_only).order(email: :asc)
      @campers_only_list_text = @campers_only_list.join(",\n")

      might_go_user_ids = ::User.with_plan(:none, :thinking_about_it, :camping_with_us).pluck(:id).compact
      @might_go_list = ::Newsletter.subscribed.where(user_id: might_go_user_ids).order(email: :asc)
      @might_go_list_text = @might_go_list.join(",\n")

      no_plan_user_ids = ::User.with_plan(:none).pluck(:id).compact
      @no_plan_list = ::Newsletter.subscribed.where(user_id: no_plan_user_ids).order(email: :asc)
      @no_plan_list_text = @no_plan_list.join(",\n")

      wap_user_ids = ::CampWorkAccessPass.pluck(:user_id).compact
      @wap_list = ::Newsletter.subscribed.where(user_id: wap_user_ids).order(email: :asc)
      @wap_list_text = @wap_list.join(",\n")

      job_user_ids = ::CampJob.includes(:camp_job_description).where("camp_job_descriptions.department = ?", ::CampJobDescription.department.find_value(:kitchen).value).pluck(:user_id).compact
      @kitchen_list = ::User.where(id: job_user_ids).order(email: :asc)
      @kitchen_list_text = @kitchen_list.map(&:email).compact.uniq.join(",\n")

      paid_dues_user_ids = ::CampDue.finished.pluck(:user_id).compact.uniq
      paid_deposit_user_ids = ::CampDeposit.finished.pluck(:user_id).compact.uniq

      dues_without_depoit_user_ids = paid_dues_user_ids - paid_deposit_user_ids
      @dues_without_deposit_list = ::User.where(id: dues_without_depoit_user_ids).order(email: :asc)
      @dues_without_deposit_list_text = @dues_without_deposit_list.map(&:email).compact.uniq.join(",\n")

      @camping_with_us_active_list = ::User.with_plan(:camping_with_us).with_status(:active)
      @camping_with_us_active_list_text = @camping_with_us_active_list.map(&:email).compact.uniq.join(",\n")

      @camping_with_us_confirmed_list = ::User.with_plan(:camping_with_us).with_status(:confirmed)
      @camping_with_us_confirmed_list_text = @camping_with_us_confirmed_list.map(&:email).compact.uniq.join(",\n")
    end

    # PATCH /admin/users/:id/restore
    def restore
      @newsletter.undiscard

      redirect_to(admin_newsletter_url(@newsletter), notice: "Newsletter was successfully restored.", status: :see_other)
    end

    # DELETE /admin/users/:id/force_delete
    def force_delete
      @newsletter.delete

      redirect_to(admin_root_url, notice: "Newsletter was been deleted.", status: :see_other)
    end

    # PATCH /admin/newsletters/:id/unsubscribe
    def unsubscribe
      @newsletter.unsubscribe!
      redirect_to(admin_newsletter_url(@newsletter), notice: "Unsubscribe successfully completed.", status: :see_other)
    end

    private

    def set_newsletter
      @newsletter = ::Newsletter.find(params[:id])
      authorize([:admin, @newsletter])
    end
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy, :unsubscribe]

  # GET /newsletters
  def index
    authorize(:newsletter)

    if current_user && current_user.newsletter.present?
      redirect_to(newsletter_url(current_user.newsletter), notice: "We found your subscription.")
    else
      redirect_to(new_newsletter_url)
    end
  end

  # GET /newsletters/:id
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = ::Newsletter.new(email: params[:email])
    authorize(@newsletter)
  end

  # POST /newsletters
  def create
    @newsletter = ::Newsletter.kept.for_user(current_user).take if current_user

    if @newsletter.present?
      @newsletter.assign_attributes(permitted_attributes(::Newsletter))
    else
      @newsletter = ::Newsletter.new(permitted_attributes(::Newsletter))
      @newsletter.user = current_user
    end

    authorize(@newsletter)
    @newsletter.list = :general if @newsletter.list == :unsubscribed

    if @newsletter.save
      if current_user
        redirect_to(newsletter_url(@newsletter), success: "Subscription has been created.")
      else
        redirect_to(root_url, success: "Subscription has been created.")
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /newsletters/:id/edit
  def edit
  end

  # PATCH /newsletters/:id
  def update
    if @newsletter.update(permitted_attributes(@newsletter))
      redirect_to(newsletter_url(@newsletter), success: "Subscription has been successfully updated.")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /newsletters/:id
  def destroy
    @newsletter.unsubscribe!

    redirect_to(root_url, notice: "You are now unsubscribed.", status: :see_other)
  end

  # PATCH /newsletters/:id/unsubscribe
  def unsubscribe
    @newsletter.unsubscribe!

    redirect_to(root_url, notice: "You are now unsubscribed.", status: :see_other)
  end

  private

  def set_newsletter
    @newsletter = ::Newsletter.kept.find(params[:id])
    authorize(@newsletter)
  end
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
  def newsletter_list_badge(newsletter)
    return na_badge unless newsletter&.list.present?

    css_class =
      case newsletter.list.to_sym
      when :unsubscribed then "badge bg-secondary"
      when :general then "badge bg-primary"
      when :campers_only then "badge bg-success"
      else
        "badge bg-dark"
      end

    tag.span(newsletter.list&.to_s&.humanize, class: css_class)
  end
end

app/views/admin/newsletters/_actions_card.html.slim
.card.mb-3
  = card_header("send", "Actions")
  .card-body
    .btn-collection
      - if policy([:admin, :newsletter]).export?
        = link_to("Export", export_admin_newsletters_path, class: "btn btn-warning")

app/views/admin/newsletters/_admin_card.html.slim
.card.mb-3
  = card_header("shield-check text-danger", "Admin", buttons: [header_admin_delete_button(resource)])
  .card-body
    .btn-collection
      - if resource.subscribed? && policy([:admin, resource]).unsubscribe?
        = link_to("Unsubscribe", unsubscribe_admin_newsletter_path(resource), class: "btn btn-warning", data: {turbo_confirm: "Are you sure?", turbo_method: :patch})
      - if resource.discarded? && policy([:admin, resource]).force_delete?
        = link_to("Force delete", polymorphic_path([:admin, resource], action: :force_delete), class: "btn btn-dark", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"})

app/views/admin/newsletters/_form.html.slim
= render "shared/error_messages", resource: resource
= simple_form_for([:admin, resource]) do |f|
  .row
    .col-md-6.mb-3
      = f.input :email
    - if current_user.mayor?
      .col-md-6.mb-3
        = f.input :user_id, label: "User ID"
  .row
    .col-md-6.mb-3
      = f.input :list, include_blank: false
  .row
    .col.d-grid
      = f.button :submit, submit_button_text(resource)

app/views/admin/newsletters/_newsletter_card.html.slim
.card.mb-3
  = card_header("envelope-open", admin_link_to_camp(@newsletter, "Subscription"), buttons: [header_show_button(@newsletter), header_admin_edit_button(@newsletter)])
  .card-table
    table.table
      tbody
        tr
          th ID
          td = admin_link_to_id(@newsletter)
        tr
          th User
          td = admin_link_to_user(@newsletter.user)
        tr
          th List
          td = newsletter_list_badge(@newsletter)
        tr
          th Unsubscribed
          td = admin_time(@newsletter.unsubscribed_at)
        tr
          th Created
          td = admin_time(@newsletter.created_at)
        tr
          th Updated
          td = admin_time(@newsletter.updated_at)

app/views/admin/newsletters/_search_card.html.slim
.card.mb-3
  = card_header("search", "Search")
  .card-form
    = simple_form_for(:search, url: admin_newsletters_path, method: :get) do |f|
      .row
        .col-md-6.mb-3
           = f.input :email, as: :string, input_html: { value: params.dig(:search, :email) }, label: "Email", required: false
        .col-md-6.mb-3
          = f.input :list, collection: ::Newsletter.list.values.sort, selected: params.dig(:search, :list), label_method: :humanize, label: "List", include_blank: true, required: false
      .row
        .col-md-6.mb-3
           = f.input :user_id, input_html: { value: params.dig(:search, :user_id) }, label: "User ID", required: false
      .row
        .col.d-grid
          = f.button :button, "Search"

app/views/admin/newsletters/_table_card.html.slim
= turbo_frame_tag("newsletters_card", target: "_top") do
  .card.mb-3
    = card_header("envelope-open", "Subscriptions", pagy: pagy, buttons: [header_admin_new_button(:newsletter)])
    .card-table
      table.table
        thead
          tr
            th = admin_table_sort(path: :newsletters, column: "id", label: "ID")
            th = admin_table_sort(path: :newsletters, column: "email", label: "Email")
            th User
            th = admin_table_sort(path: :newsletters, column: "list", label: "List")
            th
        tbody
          - resources.each do |newsletter|
            tr class=table_row_class(newsletter)
              td = admin_link_to_id(newsletter)
              td = mail_to(newsletter.email, target: "_blank")
              td = admin_link_to_user(newsletter.user)
              td = newsletter_list_badge(newsletter)
              td.text-end = admin_edit_icon(newsletter)

    = pagy_card_footer(pagy)

app/views/admin/newsletters/edit.html.slim
- page_title("Edit #{@newsletter}")

.row
  .col-md-3
  .col-md-6
    .card.mb-3
      = card_header("envelope-open", "Subscription", buttons: [header_admin_back_button(@newsletter)])
      .card-form
        = render "form", resource: @newsletter
  .col-md-3

app/views/admin/newsletters/export.html.slim
- page_title("Export")

.row
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "General list", pagy: @general_list.size)
      .card-body
        textarea.form-control.text rows="10" = @general_list_text
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "Campers only list", pagy: @campers_only_list.size)
      .card-body
        textarea.form-control.text rows="10" = @campers_only_list_text
  .col-md-4
    .card.bg-info.bg-opacity-25.mb-3
      = card_header("info-circle", "Info")
      .card-body
        p.card-text Remember to <b>BCC</b> everyone!

.row
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "Might go list", pagy: @might_go_list.size)
      .card-body
        textarea.form-control.text rows="10" = @might_go_list_text
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "No plan list", pagy: @no_plan_list.size)
      .card-body
        textarea.form-control.text rows="10" = @no_plan_list_text
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "WAP list", pagy: @wap_list.size)
      .card-body
        textarea.form-control.text rows="10" = @wap_list_text
.row
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "Kitchen list", pagy: @kitchen_list.size)
      .card-body
        textarea.form-control.text rows="10" = @kitchen_list_text
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "Dues without deposit", pagy: @dues_without_deposit_list.size)
      .card-body
        textarea.form-control.text rows="10" = @dues_without_deposit_list_text
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "Active", pagy: @camping_with_us_active_list.size)
      .card-body
        textarea.form-control.text rows="10" = @camping_with_us_active_list_text
  .col-md-4
    .card.mb-3
      = card_header("mailbox", "Confirmed", pagy: @camping_with_us_confirmed_list.size)
      .card-body
        textarea.form-control.text rows="10" = @camping_with_us_confirmed_list_text

app/views/admin/newsletters/index.html.slim
- page_title("Subscriptions")
.row
  .col-md-8
    = render "search_card"
  .col-md-4
    = render "actions_card"
.row
  .col-md-12
    = render "table_card", resources: @newsletters, pagy: @pagy

app/views/admin/newsletters/new.html.slim
- page_title("Subscribe")

.row
  .col-md-3
  .col-md-6
    .card.mb-3
      = card_header("envelope-open", "Subscription")
      .card-form
        = render "form", resource: @newsletter
  .col-md-3

app/views/admin/newsletters/show.html.slim
- page_title(@newsletter)
= discard_alert(@newsletter)

.row
  .col-md-3
  .col-md-6
    = render "newsletter_card", resource: @newsletter
  .col-md-3
    = render "admin_card", resource: @newsletter