config/routes.rb
Rails.application.routes.draw do
  get "401", to: "errors#unauthorized", as: :unauthorized_error
  get "403", to: "errors#forbidden", as: :forbidden_error
  get "404", to: "errors#not_found", as: :not_found_error
  get "406", to: "errors#not_acceptable", as: :not_acceptable_error
  get "422", to: "errors#unprocessable_entity", as: :unprocessable_entity_error
  get "500", to: "errors#internal_server_error", as: :internal_server_error_error

  namespace :admin do
    resource :camp, only: [:show]

    resources :camp_applications do
      member do
        patch :active
        patch :approve
        patch :complete
        delete :force_delete
        patch :reject
        patch :restore
      end
    end

    resources :camp_deposits do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_dues do
      member do
        patch :active
        patch :complete
        patch :pay
        patch :refund
        patch :reject
        patch :skip
      end
    end

    resources :camp_interviews do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        delete :force_delete
        patch :no_response
        patch :skip
        patch :reassign
        patch :restore
        patch :reject
      end
    end

    resources :camp_job_descriptions do
      member do
        patch :active
      end
    end

    resources :camp_jobs do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :skip
        patch :reject
      end
    end

    resources :camp_structures do
      member do
        patch :active
        patch :approve
        patch :assign
        patch :complete
        patch :reject
      end
    end

    resources :camp_tickets

    resources :camp_vehicles do
      member do
        patch :active
        patch :approve
        patch :complete
        patch :reject
      end
    end

    resources :camp_work_access_passes do
      collection do
        get :print_all
      end

      member do
        patch :active
        patch :approve
        patch :assign
        patch :reject
        patch :remove_ticket
      end
    end

    resources :newsletters do
      collection do
        get :export
      end

      member do
        delete :force_delete
        patch :restore
        patch :unsubscribe
      end
    end

    resources :pages, only: [] do
      collection do
        get :system
      end
    end

    resources :users do
      collection do
        get :bay_area
        get :deleted
        get :interviewers
        get :print_all
      end

      member do
        patch :remove_avatar
        get :print
        patch :restore
      end
    end

    root to: "pages#home"
  end

  resources :camp_applications, except: [:destroy] do
    collection do
      get :start
    end
  end

  resources :camp_deposits, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_dues, except: [:destroy] do
    member do
      patch :pay
    end
  end

  resources :camp_interviews, only: [:index, :show] do
    member do
      patch :approve_or_reject
    end
  end

  resources :camp_job_descriptions, only: [:index, :show]
  resources :camp_jobs, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :camp_structures

  resources :camp_tickets

  resources :camp_vehicles

  resources :camp_work_access_passes, only: [:index, :show, :edit, :update] do
    member do
      patch :sign_up
      patch :remove
    end
  end

  resources :guides, only: [:index] do
    collection do
      get :build
      get :bunny_bar
      get :covid
      get :deposit
      get :disclaimer
      get :dues
      get :events
      get :history
      get :ice
      get :interview
      get :jobs
      get :kitchen
      get :lag_bolts
      get :learn
      get :map
      get :mayor_of_the_day
      get :outside_services
      get :parking
      get :power
      get :projects
      get :rules
      get :sauna
      get :shade
      get :shipping_container
      get :sound
      get :strike
      get :tickets
      get :tools
      get :trash
      get :work_access_pass
      get :yearbook
    end
  end

  resources :newsletters do
    member do
      patch :unsubscribe
    end
  end

  resources :pages, only: [] do
    collection do
      get :contact
      get :events
      get :history
    end
  end

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_calbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  resources :users, only: [:index, :show, :edit] do
    member do
      patch :confirm
      get :ticket
    end

    collection do
      get :me
      get :search
      get :status
    end
  end

  root to: "pages#home"
end

app/controllers/admin/camp_interviews_controller.rb
module Admin
  class CampInterviewsController < ApplicationController
    include Admin::Campable

    # GET /admin/camp_interviews
    def index
      authorize([:admin, :camp_interview])
      @query = ::CampInterview.includes(:user, :interviewed_by).order(updated_at: :desc)

      @query = @query.for_interviewed_by(params[:search][:interviewed_by_id]) if params.dig(:search, :interviewed_by_id).present?

      @query = @query.with_status(params[:search][:status]) if params.dig(:search, :status).present?

      @pagy, @resources = pagy(@query)
    end

    # PATCH /admin/camp_interviews/:id/assign
    def assign
      set_resource

      @interviewed_by = ::User.for_id(params.dig(:camp_interview, :interviewed_by_id)).take
      @resource.assigned_at = Time.current
      @resource.assigned_by = current_user
      @resource.interviewed_by = @interviewed_by
      @resource.status = :assigned

      @resource.assign_attributes(permitted_attributes([:admin, @resource])) if params[:camp_interview].present?

      if @resource.save
        CampInterviewMailer.with(resource: @resource).assign.deliver_now if send_email?
        CampInterviewMailer.with(resource: @resource).new_interview.deliver_now if send_email?

        redirect_to([:admin, @resource], success: "Interview has been assigned to #{@interviewed_by}.", status: :see_other)
      else
        redirect_on_error
      end
    end

    # PATCH /admin/camp_interviews/:id/reassign
    def reassign
      set_resource

      @interviewed_by = ::User.for_id(params.dig(:camp_interview, :interviewed_by_id)).take
      @resource.assigned_at = Time.current
      @resource.assigned_by = current_user
      @resource.interviewed_by = @interviewed_by
      @resource.status = :assigned

      @resource.assign_attributes(permitted_attributes([:admin, @resource])) if params[:camp_interview].present?

      if @resource.save
        CampInterviewMailer.with(resource: @resource).reassign.deliver_now if send_email?
        CampInterviewMailer.with(resource: @resource).new_interview.deliver_now if send_email?

        redirect_to([:admin, @resource], success: "Interview has been reassigned to #{@interviewed_by}.", status: :see_other)
      else
        redirect_on_error
      end
    end

    private

    def approve_after_save
      return unless @resource.user.present?
      @resource.user.update(plan: :camping_with_us)

      CampInterviewMailer.with(resource: @resource).approve.deliver_now if send_email?
    end

    def complete_after_save
      return unless @resource.user.present?

      @resource.user.update(plan: :camping_with_us)
    end

    def reject_after_save
      return unless @resource.user.present?
      @resource.user.update(plan: :camping_elsewhere)

      CampInterviewMailer.with(resource: @resource).reject.deliver_now if send_email?
    end

    def skip_after_save
      return unless @resource.user.present?
      @resource.user.update(plan: :camping_with_us)
      @resource.update(interviewed_by: nil)

      CampInterviewMailer.with(resource: @resource).skip.deliver_now if send_email?
    end
  end
end

app/controllers/camp_interviews_controller.rb
class CampInterviewsController < ApplicationController
  include Campable

  # GET /camp_interviews
  def index
    authorize(:camp_interview)
    @assigned_camp_interviews_pagy, @assigned_camp_interviews = pagy(current_user.camp_interviews.with_status(:assigned).includes([:user, :assigned_by]))
    @finished_camp_interviews_pagy, @finished_camp_interviews = pagy(current_user.camp_interviews.with_status(:approved, :completed, :no_response, :rejected).includes([:user, :assigned_by, :interviewed_by]))
  end

  # PATCH /camp_interviews/:id/approve_or_reject
  def approve_or_reject
    set_resource

    @resource.assign_attributes(permitted_attributes(@resource))

    case params.dig(:camp_interview, :action)&.to_sym
    when :approved then approve
    when :rejected then reject
    when :no_response then no_response
    else
      no_action
    end

    render(
      turbo_stream: turbo_stream.replace(
        "approve_or_reject_card_#{@resource.index}",
        partial: "camp_interviews/approve_or_reject_card",
        locals: {index: @resource.index, camp_interview: @resource}
      )
    )
  end

  private

  def approve
    @resource.status = :approved
    @resource.approved_by = current_user
    @resource.approved_at = Time.current

    if @resource.save && @resource.user.present?
      CampInterviewMailer.with(resource: @resource).approve.deliver_now
      CampInterviewMailer.with(resource: @resource).admin_approve.deliver_now
      @resource.user.update(plan: :camping_with_us)
    end
  end

  def reject
    @resource.status = :rejected
    @resource.rejected_by = current_user
    @resource.rejected_at = Time.current

    if @resource.save && @resource.user.present?
      CampInterviewMailer.with(resource: @resource).reject.deliver_now
      CampInterviewMailer.with(resource: @resource).admin_reject.deliver_now
      @resource.user.update(plan: :camping_elsewhere)
    end
  end

  def no_response
    previous_status = @resource.status.to_sym
    @resource.status = :no_response
    @resource.no_response_by = current_user
    @resource.no_response_at = Time.current

    if @resource.save && @resource.user.present? && previous_status != :no_response
      CampInterviewMailer.with(resource: @resource).no_response.deliver_now
    end
  end

  def no_action
    @resource.errors.add(:action, "is required")
  end
end

app/helpers/camp_interview_helper.rb
module CampInterviewHelper
  def camp_interviews_count_badge(count)
    return na_badge unless count.present?

    if count.zero?
      success_count_badge(count)
    else
      warning_count_badge(count)
    end
  end
end

app/views/admin/camp_interviews/_approve_card.html.slim
- if [:rejected, :completed, :approved, :skipped].exclude?(resource.status.to_sym) && policy([:admin, resource]).approve?
  .card.mb-3
    = card_header("check-circle", "Approve")
    .card-form
      = simple_form_for([:admin, resource], namespace: "approve", url: approve_admin_camp_interview_path(resource)) do |f|
        .row
          .col.mb-3
            = f.input :feedback_notes, hint: "shown to user"
        .row
          .col.mb-3
            = f.input :private_notes, hint: "only visible to camp leadership"
        .row
          .col.mb-3
            = f.input :send_email
        .row
          .col.d-grid
            = f.button :submit, "Approve", class: "btn-primary-override"

app/views/admin/camp_interviews/_assign_card.html.slim
- if [:rejected, :completed, :approved, :assigned].exclude?(resource.status.to_sym) && policy([:admin, resource]).assign?
  .card.mb-3
    = card_header("save", "Assign")
    .card-body
      = simple_form_for([:admin, resource], namespace: "assign", url: assign_admin_camp_interview_path(resource)) do |f|
        .row
          .col.mb-3
            = f.input :interviewed_by_id, collection: ::User.with_role(:leader, :mayor).order_by_name, label: "Interviewer", label_method: :full_name, prompt: "Choose a user", required: true
        .row
          .col.mb-3
            = f.input :initial_notes
        .row
          .col.mb-3
            = f.input :send_email
        .row
          .col.d-grid
            = f.button :submit, "Assign", class: "btn-primary-override"

app/views/admin/camp_interviews/_camp_interview_card.html.slim
.card.mb-3
  = card_header("file-earmark-person", admin_link_to_camp(resource, "Interview"), buttons: [header_show_button(resource), header_admin_edit_button(resource)])
  .card-table
    table.table
      tbody
        tr
          th ID
          td = admin_link_to_id(resource)
        tr
          th User
          td = admin_link_to_user(resource.user)
        tr
          th Status
          td = camp_status_badge(resource)
        tr
          th Initial notes
          td = resource.initial_notes.presence || na_badge
        tr
          th Feedback notes
          td = resource.feedback_notes.presence || na_badge
        tr
          th Private notes
          td = resource.private_notes.presence || na_badge
        tr
          th Interviewer
          td = admin_link_to_user(resource.interviewed_by)
        = render "admin/shared/status_times", resource: resource

app/views/admin/camp_interviews/_complete_card.html.slim
- if [:rejected, :completed].exclude?(resource.status.to_sym) && policy([:admin, resource]).complete?
  .card.mb-3
    = card_header("clipboard-check", "Complete")
    .card-body
      = simple_form_for([:admin, resource], url: complete_admin_camp_interview_path(resource)) do |f|
        .row
          .col.d-grid
            = f.button :submit, "Complete", class: "btn-success-override"

app/views/admin/camp_interviews/_form.html.slim
= render "shared/error_messages", resource: resource
= simple_form_for([:admin, resource]) do |f|
  .row
    .col-md-6.mb-3
      = f.input :status, include_blank: false
    .col-md-6.mb-3
      = user_id_input(resource, f)
  .row
    .col-md-12.mb-3
      = f.input :initial_notes, hint: "intro to the interview"
  .row
    .col-md-12.mb-3
      = f.input :feedback_notes, hint: "let the person know how they did"
  .row
    .col-md-12.mb-3
      = f.input :private_notes, hint: "share your concerns with camp leadership"
  .row
    .col.d-grid
      = f.button :submit, submit_button_text(resource)

app/views/admin/camp_interviews/_reassign_card.html.slim
- if [:assigned].include?(resource.status.to_sym) && policy([:admin, resource]).reassign?
  .card.mb-3
    = card_header("save", "Reassign")
    .card-body
      = simple_form_for([:admin, resource], namespace: "reassign", url: reassign_admin_camp_interview_path(resource)) do |f|
        .row
          .col.mb-3
            = f.input :interviewed_by_id, collection: ::User.with_role(:leader, :mayor).order_by_name, label: "Interviewer", label_method: :full_name, prompt: "Choose a user", required: true
        .row
          .col.mb-3
            = f.input :initial_notes
        .row
          .col.mb-3
            = f.input :send_email
        .row
          .col.d-grid
            = f.button :submit, "Reassign", class: "btn-warning-override"

app/views/admin/camp_interviews/_reject_card.html.slim
- if [:completed, :rejected].exclude?(resource.status.to_sym) && policy([:admin, resource]).reject?
  .card.mb-3
    = card_header("x-octagon", "Reject")
    .card-body
      = simple_form_for([:admin, resource], namespace: "reject", url: reject_admin_camp_interview_path(resource)) do |f|
        .row
          .col.mb-3
            = f.input :feedback_notes, hint: "shown to user"
        .row
          .col.mb-3
            = f.input :private_notes, hint: "only visible to camp leadership"
        .row
          .col.mb-3
            = f.input :send_email
        .row
          .col.d-grid
            = f.button :submit, "Reject", class: "btn-danger-override"

app/views/admin/camp_interviews/_search_card.html.slim
.card.mb-3
  = card_header("search", "Search")
  .card-form
    = simple_form_for(:search, url: admin_camp_interviews_path, method: :get) do |f|
      .row
        .col-md-4.mb-3
          = f.input :status, collection: ::CampInterview.status.values.sort, selected: params.dig(:search, :status), label_method: :humanize, include_blank: true, required: false
        .col-md-4.mb-3
          = f.input :interviewed_by_id, collection: ::User.with_role(:leader, :mayor).order_by_name, selected: params.dig(:search, :interviewed_by_id), label_method: :full_name, include_blank: true, required: false
      .row
        .col.d-grid
          = f.button :button, "Search"

app/views/admin/camp_interviews/_skip_card.html.slim
- if [:rejected, :completed, :approved, :assigned, :skipped].exclude?(resource.status.to_sym) && policy([:admin, resource]).skip?
  .card.mb-3
    = card_header("skip-forward-circle", "Skip")
    .card-body
      = simple_form_for([:admin, resource], namespace: "skip", url: skip_admin_camp_interview_path(resource)) do |f|
        .row
          .col.mb-3
            = f.input :private_notes
        .row
          .col.mb-3
            = f.input :feedback_notes, hint: "shown to user"
        .row
          .col.mb-3
            = f.input :send_email
        .row
          .col.d-grid
            = f.button :submit, "Skip", class: "btn-info-override"

app/views/admin/camp_interviews/_table_card.html.slim
.card.mb-3
  = card_header("file-earmark-person", "Interviews", pagy: pagy, buttons: [header_admin_new_button(:camp_interview)])
  .card-table
    table.table
      thead
        tr
          th ID
          th User
          th Status
          th Interviewer
          th
      tbody
        - resources.each do |resource|
          tr class=table_row_class(resource)
            td = admin_link_to_id(resource)
            td = admin_link_to_user(resource.user)
            td = camp_status_badge(resource)
            td = admin_link_to_user(resource.interviewed_by)
            td.text-end = admin_edit_icon(resource)
  = pagy_card_footer(pagy)

app/views/admin/camp_interviews/edit.html.slim
- page_title("Edit #{@resource}")
= discard_alert(@resource)

.row
  .col-md-3
  .col-md-6
    .card.mb-3
      = card_header("file-earmark-person", "Interview", buttons: [header_admin_back_button(@resource)])
      .card-form
        = render "form", resource: @resource
  .col-md-3
    = render "admin_card", resource: @resource

app/views/admin/camp_interviews/index.html.slim
- page_title("Interviews")
.row
  .col-md-8
    = render "search_card"
.row
  .col-md-12
    = render "table_card", resources: @resources, pagy: @pagy

app/views/admin/camp_interviews/new.html.slim
- page_title("New - Interview")

.row
  .col-md-3
  .col-md-6
    .card.mb-3
      = card_header("file-earmark-person", "Interview")
      .card-form
        = render "form", resource: @resource
  .col-md-3

app/views/admin/camp_interviews/show.html.slim
- page_title(@resource)
= discard_alert(@resource)

.row
  .col-md-3
  .col-md-6
    = render "camp_interview_card", resource: @resource
  .col-md-3
    = render "assign_card", resource: @resource
    = render "approve_card", resource: @resource
    = render "skip_card", resource: @resource
    = render "complete_card", resource: @resource
    = render "reassign_card", resource: @resource
    = render "reject_card", resource: @resource
    = render "admin_card", resource: @resource